{
 "title": "System Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "component", "query": { "query": "label_values(component)" } }
  ]
 },
 "panels": [
  {
   "title": "GPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "GPUClockEventReason_Max{identifier=\"4LRZYY3\", component=\"$component\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Primary Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "PrimaryTemperature_Avg{component=\"$component\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "PrimaryTemperature_Max{component=\"$component\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "CPUUsage_Max{identifier=\"4LRZYY3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "CPUUsage_Avg{identifier=\"4LRZYY3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "CPUUsage_Min{identifier=\"4LRZYY3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "PowerConsumption_Avg{identifier=\"4LRZYY3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "PowerConsumption_Max{identifier=\"4LRZYY3\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}