{
 "title": "Telemetry Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "identifier", "label": "system_id", "query": { "query": "label_values(identifier)" } },
   {
    "name": "component",
    "label": "type",
    "query": {
     "query": "label_values({identifier=~\"$identifier\"}, component)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "GPUClockEventReason_Max{identifier=~\"$identifier\", component=~\"$component\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Primary Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "PrimaryTemperature_Avg{identifier=~\"$identifier\", component=~\"$component\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "PrimaryTemperature_Max{identifier=~\"$identifier\", component=~\"$component\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "CPUUsage_Max{identifier=~\"$identifier\", component=\"System\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "CPUUsage_Avg{identifier=~\"$identifier\", component=\"System\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "CPUUsage_Min{identifier=~\"$identifier\", component=\"System\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "PowerConsumption_Avg{identifier=~\"$identifier\", component=~\"$component\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "PowerConsumption_Max{identifier=~\"$identifier\", component=~\"$component\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}